/*
 * Copyright (C) 2024 koalium
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package departed;


import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author koalium
 */
public class Control extends javax.swing.JFrame {

	

	/**
	 * Creates new form control
	 */
	public Control() {
		initComponents();
		getfpressure();
		getfheight();
		getcdepend();
		getcduty();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jOptionPaneRun = new javax.swing.JOptionPane();
                jPanelControl = new javax.swing.JPanel();
                jPanel13 = new javax.swing.JPanel();
                jPanel18 = new javax.swing.JPanel();
                jPanel14 = new javax.swing.JPanel();
                jScrollBarPwm = new javax.swing.JScrollBar();
                jLabelPwm = new javax.swing.JLabel();
                jPanel20 = new javax.swing.JPanel();
                jButtonPump = new javax.swing.JButton();
                jButtonPause = new javax.swing.JButton();
                jToggleButtonValveDrain = new javax.swing.JToggleButton();
                jPanel21 = new javax.swing.JPanel();
                jPanelValve = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jPanelState = new javax.swing.JPanel();
                jLabelState = new javax.swing.JLabel();
                jPanel16 = new javax.swing.JPanel();
                jPanel17 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jButtonRun = new javax.swing.JButton();
                jPanel6 = new javax.swing.JPanel();
                jButtonStop = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jPanel11 = new javax.swing.JPanel();
                jFormattedTextFieldPressure = new javax.swing.JFormattedTextField();
                jRadioButtonPressure = new javax.swing.JRadioButton();
                jPanel12 = new javax.swing.JPanel();
                jFormattedTextFieldHeghit = new javax.swing.JFormattedTextField();
                jRadioButtonHeight = new javax.swing.JRadioButton();

                jOptionPaneRun.setMessage(""+fheight);
                jOptionPaneRun.setValue(jFormattedTextFieldHeghit);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Control Forming");
                setLocation(new java.awt.Point(10, 453));
                setName("frameControl"); // NOI18N

                jPanelControl.setBackground(new java.awt.Color(153, 153, 255));
                jPanelControl.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)), javax.swing.BorderFactory.createTitledBorder(null, "Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0)))); // NOI18N
                jPanelControl.setForeground(new java.awt.Color(204, 204, 255));

                jPanel13.setBackground(new java.awt.Color(153, 153, 255));
                jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jPanel18.setBackground(new java.awt.Color(153, 153, 255));

                jPanel14.setBackground(new java.awt.Color(153, 153, 255));
                jPanel14.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Motor Power", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), java.awt.Color.black), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.darkGray))); // NOI18N

                jScrollBarPwm.setBackground(new java.awt.Color(204, 255, 204));
                jScrollBarPwm.setForeground(new java.awt.Color(102, 204, 0));
                jScrollBarPwm.setMaximum(256);
                jScrollBarPwm.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
                jScrollBarPwm.setToolTipText("");
                jScrollBarPwm.setUnitIncrement(4);
                jScrollBarPwm.setVisibleAmount(1);
                jScrollBarPwm.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
                        public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                                jScrollBarPwmAdjustmentValueChanged(evt);
                        }
                });

                jLabelPwm.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
                jLabelPwm.setForeground(new java.awt.Color(0, 0, 0));
                jLabelPwm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelPwm.setText("0");

                javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
                jPanel14.setLayout(jPanel14Layout);
                jPanel14Layout.setHorizontalGroup(
                        jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollBarPwm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPwm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanel14Layout.setVerticalGroup(
                        jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelPwm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollBarPwm, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                                .addGap(7, 7, 7))
                );

                javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
                jPanel18.setLayout(jPanel18Layout);
                jPanel18Layout.setHorizontalGroup(
                        jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel18Layout.setVerticalGroup(
                        jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel18Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jPanel20.setBackground(new java.awt.Color(153, 153, 255));
                jPanel20.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED))));

                jButtonPump.setBackground(java.awt.Color.cyan);
                jButtonPump.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
                jButtonPump.setForeground(new java.awt.Color(0, 0, 0));
                jButtonPump.setText("Pump");
                jButtonPump.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jButtonPumpMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jButtonPumpMouseReleased(evt);
                        }
                });

                jButtonPause.setBackground(java.awt.Color.magenta);
                jButtonPause.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
                jButtonPause.setForeground(new java.awt.Color(0, 0, 0));
                jButtonPause.setText("Pause");
                jButtonPause.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jButtonPauseMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jButtonPauseMouseReleased(evt);
                        }
                });

                jToggleButtonValveDrain.setBackground(java.awt.Color.pink);
                jToggleButtonValveDrain.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
                jToggleButtonValveDrain.setForeground(new java.awt.Color(0, 0, 0));
                jToggleButtonValveDrain.setText("Drain");
                jToggleButtonValveDrain.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jToggleButtonValveDrainActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
                jPanel20.setLayout(jPanel20Layout);
                jPanel20Layout.setHorizontalGroup(
                        jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel20Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonPump)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(jButtonPause)
                                .addGap(74, 74, 74)
                                .addComponent(jToggleButtonValveDrain)
                                .addContainerGap())
                );
                jPanel20Layout.setVerticalGroup(
                        jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonPause, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                        .addComponent(jButtonPump, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jToggleButtonValveDrain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jPanel21.setBackground(new java.awt.Color(153, 153, 255));
                jPanel21.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED))));

                jPanelValve.setBackground(new java.awt.Color(0, 153, 153));
                jPanelValve.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createTitledBorder(null, "Drain Valve", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0)))); // NOI18N

                jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
                jLabel2.setForeground(java.awt.Color.black);
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("Closed");

                javax.swing.GroupLayout jPanelValveLayout = new javax.swing.GroupLayout(jPanelValve);
                jPanelValve.setLayout(jPanelValveLayout);
                jPanelValveLayout.setHorizontalGroup(
                        jPanelValveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelValveLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelValveLayout.setVerticalGroup(
                        jPanelValveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelValveLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanelState.setBackground(new java.awt.Color(0, 204, 204));
                jPanelState.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createTitledBorder(null, "State ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0)))); // NOI18N

                jLabelState.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
                jLabelState.setForeground(java.awt.Color.black);
                jLabelState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelState.setText("idle");

                javax.swing.GroupLayout jPanelStateLayout = new javax.swing.GroupLayout(jPanelState);
                jPanelState.setLayout(jPanelStateLayout);
                jPanelStateLayout.setHorizontalGroup(
                        jPanelStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStateLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelState, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelStateLayout.setVerticalGroup(
                        jPanelStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelStateLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
                jPanel21.setLayout(jPanel21Layout);
                jPanel21Layout.setHorizontalGroup(
                        jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel21Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelValve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(jPanelState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanel21Layout.setVerticalGroup(
                        jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                .addContainerGap(11, Short.MAX_VALUE)
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelValve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(
                        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                );
                jPanel13Layout.setVerticalGroup(
                        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jPanel16.setBackground(new java.awt.Color(153, 153, 255));

                jPanel17.setBackground(new java.awt.Color(153, 153, 255));
                jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 102, 102), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 0), new java.awt.Color(0, 102, 102)));

                jPanel4.setBackground(new java.awt.Color(153, 153, 255));
                jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED))));

                jButtonRun.setBackground(new java.awt.Color(102, 255, 51));
                jButtonRun.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jButtonRun.setForeground(java.awt.Color.black);
                jButtonRun.setText("Run");
                jButtonRun.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jButtonRunMousePressed(evt);
                        }
                });
                jButtonRun.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonRunActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonRun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jPanel6.setBackground(new java.awt.Color(153, 153, 255));
                jPanel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder())));
                jPanel6.setPreferredSize(new java.awt.Dimension(120, 112));

                jButtonStop.setBackground(java.awt.Color.red);
                jButtonStop.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jButtonStop.setForeground(java.awt.Color.black);
                jButtonStop.setText("Stop");
                jButtonStop.setPreferredSize(new java.awt.Dimension(92, 84));
                jButtonStop.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jButtonStopMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jButtonStopMouseReleased(evt);
                        }
                });
                jButtonStop.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonStopActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonStop, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
                jPanel17.setLayout(jPanel17Layout);
                jPanel17Layout.setHorizontalGroup(
                        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel17Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanel17Layout.setVerticalGroup(
                        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jPanel3.setBackground(new java.awt.Color(153, 153, 255));

                jPanel11.setBackground(new java.awt.Color(153, 153, 255));
                jPanel11.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pressure", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED))); // NOI18N
                jPanel11.setForeground(new java.awt.Color(153, 153, 255));

                jFormattedTextFieldPressure.setBackground(new java.awt.Color(102, 102, 102));
                jFormattedTextFieldPressure.setColumns(6);
                jFormattedTextFieldPressure.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
                jFormattedTextFieldPressure.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jFormattedTextFieldPressure.setText("102.33");
                jFormattedTextFieldPressure.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

                jRadioButtonPressure.setBackground(new java.awt.Color(153, 153, 255));
                jRadioButtonPressure.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jRadioButtonPressure.setForeground(new java.awt.Color(0, 0, 0));
                jRadioButtonPressure.setText("pressure");
                jRadioButtonPressure.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
                jRadioButtonPressure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jRadioButtonPressure.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
                jRadioButtonPressure.setIconTextGap(5);
                jRadioButtonPressure.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioButtonPressureActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
                jPanel11.setLayout(jPanel11Layout);
                jPanel11Layout.setHorizontalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonPressure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jFormattedTextFieldPressure, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel11Layout.setVerticalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFormattedTextFieldPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonPressure)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanel12.setBackground(new java.awt.Color(153, 153, 255));
                jPanel12.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Height", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED))); // NOI18N

                jFormattedTextFieldHeghit.setBackground(new java.awt.Color(102, 102, 102));
                jFormattedTextFieldHeghit.setColumns(5);
                jFormattedTextFieldHeghit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
                jFormattedTextFieldHeghit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jFormattedTextFieldHeghit.setText("22.23");
                jFormattedTextFieldHeghit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
                jFormattedTextFieldHeghit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                jFormattedTextFieldHeghit.setPreferredSize(new java.awt.Dimension(98, 27));
                jFormattedTextFieldHeghit.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                jFormattedTextFieldHeghitFocusLost(evt);
                        }
                });

                jRadioButtonHeight.setBackground(new java.awt.Color(153, 153, 255));
                jRadioButtonHeight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jRadioButtonHeight.setForeground(new java.awt.Color(0, 0, 0));
                jRadioButtonHeight.setSelected(true);
                jRadioButtonHeight.setText("height");
                jRadioButtonHeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jRadioButtonHeight.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
                jRadioButtonHeight.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioButtonHeightActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(
                        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap(18, Short.MAX_VALUE)
                                .addComponent(jRadioButtonHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFormattedTextFieldHeghit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel12Layout.setVerticalGroup(
                        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFormattedTextFieldHeghit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonHeight)
                                .addContainerGap(27, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
                jPanel16.setLayout(jPanel16Layout);
                jPanel16Layout.setHorizontalGroup(
                        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel16Layout.setVerticalGroup(
                        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                javax.swing.GroupLayout jPanelControlLayout = new javax.swing.GroupLayout(jPanelControl);
                jPanelControl.setLayout(jPanelControlLayout);
                jPanelControlLayout.setHorizontalGroup(
                        jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelControlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE))
                );
                jPanelControlLayout.setVerticalGroup(
                        jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelControlLayout.createSequentialGroup()
                                .addContainerGap(7, Short.MAX_VALUE)
                                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButtonPumpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPumpMouseReleased
                // TODO add your handling code here:
		
		//remchage(CHANGE_BUTTON_RELEASE_PUMP);
		jButtonPump.setBackground(Color.cyan);
		//jPanelState.setBackground(Color.gray);
		//jLabelState.setText("Pause");
        }//GEN-LAST:event_jButtonPumpMouseReleased

        private void jButtonPumpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPumpMousePressed
                // TODO add your handling code here:
		remchage(CHANGE_BUTTON_PRESS_PUMP);
		jButtonPump.setBackground(Color.gray);
		jPanelState.setBackground(Color.cyan);
		jLabelState.setText("Pump");
        }//GEN-LAST:event_jButtonPumpMousePressed

        private void jButtonPauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPauseMouseReleased
                // TODO add your handling code here:
		jButtonPause.setBackground(Color.magenta);
        }//GEN-LAST:event_jButtonPauseMouseReleased

        private void jButtonStopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopMouseReleased
                // TODO add your handling code here:
		jButtonStop.setBackground(Color.red);
        }//GEN-LAST:event_jButtonStopMouseReleased

        private void jButtonRunMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRunMousePressed
                // TODO add your handling code here:
		jButtonRun.setBackground(Color.yellow);
		remchage(CHANGE_BUTTON_PRESS_RUN);
        }//GEN-LAST:event_jButtonRunMousePressed

        private void jButtonStopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopMousePressed
                // TODO add your handling code here:
		jButtonStop.setBackground(Color.gray);
		remchage(CHANGE_BUTTON_PRESS_STOP);
        }//GEN-LAST:event_jButtonStopMousePressed

        private void jButtonPauseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPauseMousePressed
                // TODO add your handling code here:
		jButtonPause.setBackground(Color.gray);
		remchage(CHANGE_BUTTON_PRESS_PAUSE);
        }//GEN-LAST:event_jButtonPauseMousePressed

        private void jScrollBarPwmAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBarPwmAdjustmentValueChanged
                // TODO add your handling code here:
		this.cduty = jScrollBarPwm.getValue();
			jLabelPwm.setText(cduty+"");
			remchage(CHANGE_SCROLL_PWM);
        }//GEN-LAST:event_jScrollBarPwmAdjustmentValueChanged

        private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunActionPerformed
                // TODO add your handling code here:
		remchage(CHANGE_BUTTON_PRESS_RUN);
		jOptionPaneRun.validate();
		jOptionPaneRun.setVisible(true);
        }//GEN-LAST:event_jButtonRunActionPerformed

        private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
                // TODO add your handling code here:
		remchage(CHANGE_BUTTON_PRESS_STOP);
        }//GEN-LAST:event_jButtonStopActionPerformed

        private void jToggleButtonValveDrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonValveDrainActionPerformed
                // TODO add your handling code here:
		if(jToggleButtonValveDrain.isSelected()){
			jToggleButtonValveDrain.setSelected(true);
			jToggleButtonValveDrain.setBackground(Color.orange);
			
			jPanelState.setBackground(Color.orange);
			
			jLabelState.setText("Draining");
			remchage(CHANGE_BUTTON_PRESS_DRAIN);
		}else{
			jToggleButtonValveDrain.setSelected(false);
			jToggleButtonValveDrain.setBackground(Color.pink);
			
			jPanelState.setBackground(Color.pink);
			jLabelState.setText("IDLE");
			remchage(CHANGE_BUTTON_RELEASE_DRAIN);
		}
		
		
        }//GEN-LAST:event_jToggleButtonValveDrainActionPerformed

        private void jRadioButtonHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHeightActionPerformed
                // TODO add your handling code here:
		
		jRadioButtonHeight.setSelected(true);
		jRadioButtonPressure.setSelected(false);
		getcdepend();
		remchage(cdepend);
        }//GEN-LAST:event_jRadioButtonHeightActionPerformed

        private void jRadioButtonPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPressureActionPerformed
                // TODO add your handling code here:
		jRadioButtonPressure.setSelected(true);
		jRadioButtonHeight.setSelected(false);
		getcdepend();
		remchage(cdepend);
        }//GEN-LAST:event_jRadioButtonPressureActionPerformed

        private void jFormattedTextFieldHeghitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHeghitFocusLost
                // TODO add your handling code here:
		remchage(CHANGE_VALUE_HHEIGHT);
        }//GEN-LAST:event_jFormattedTextFieldHeghitFocusLost

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		
		//</editor-fold>
		
		/* Create and display the form */
		
	}
	



	private  synchronized void remchage(int ic){
		if(this.mchange%ic==0){
			return;
			
		}
		this.mchange = this.mchange*ic;
	}
	
	
	//

	//
	public void setmode(int m){
		this.cmode=m;
	}

	public final synchronized int getcduty(){
		this.cduty = jScrollBarPwm.getValue();
		return this.cduty;
	}

	//

	
	public final synchronized int getcmhange(){
		return this.mchange;
	}
	public synchronized void setmchange(int cc){
		 this.mchange=cc;
	}
	public final boolean getdrainstate(){
		return jToggleButtonValveDrain.isSelected();
	}
	public final synchronized int getcdepend(){
		if(jRadioButtonHeight.isSelected()){
				this.cdepend=CHANGE_DEPEND_HEIGHT;
			
			
		}else if(jRadioButtonPressure.isSelected()){
				this.cdepend=CHANGE_DEPEND_PRESSURE;
			
		}
		
		return this.cdepend;
	}
	public final synchronized int getfheight(){
		final float ff = Float.parseFloat(getvalue(this.jFormattedTextFieldHeghit.getText()))*100;
		
		this.fheight = (int)((ff));
		
		return this.fheight;
	}
	private final String getvalue(String s){
		if(s==null||s==""||s.length()<1){
			s="0.0";
		}
		return s;
	}
	public final synchronized int getfpressure(){
		
		final float ff = Float.parseFloat(getvalue(this.jFormattedTextFieldPressure.getText()))*100;
		
		this.fpressure = (int)((ff));
		return fpressure;
	}
	
	public synchronized int getcommand(){
		remchage(CHANGE_MODE);
		return this.mchange;
	}
	
	public synchronized void setfpressure(int cc){
		 this.fpressure=cc;
		 jFormattedTextFieldPressure.setText((float)(fpressure)/100+"");
	}
	public synchronized void setfheight(int cc){
		 this.fheight=cc;
		 jFormattedTextFieldHeghit.setText((float)(fheight)/100+"");
	}
	public synchronized void setcdepend(int cc){
		 this.cdepend=cc;
		 if(cdepend==CHANGE_DEPEND_HEIGHT){
			 jRadioButtonHeight.setSelected(true);
			 jRadioButtonPressure.setSelected(false);
		 }else{
			 jRadioButtonHeight.setSelected(false);
			 jRadioButtonPressure.setSelected(true);
		 }
	}
	Timer timer;
	private int cduty=13;
	private int mchange=1;
	private int cdepend=CHANGE_DEPEND_HEIGHT;
	public boolean running = false;
	public boolean pumping = false;
	private  int fheight =10223;
	private  int fpressure=9533;
	private  int sheight =0;
	private  int spressure=0;
	private int cmode=CHANGE_MODE_CONNECTING;
	
	public static final int ALETION_CHOOSE = 2;
	public static final int IDLE = 1;
	public static final int NONE = 0;
	public static final int CHANGE_MODE = 2;
	public static final int CHANGE_DEPEND_PRESSURE = 3;
	public static final int CHANGE_DEPEND_HEIGHT = 5;
	public static final int CHANGE_BUTTON_PRESS_RUN = 7;
	//public static final int CHANGE_BUTTON_RELEASE_RUN = 11;
	public static final int CHANGE_BUTTON_PRESS_STOP = 13;
	//public static final int CHANGE_BUTTON_RELEASE_STOP = 17;
	public static final int CHANGE_BUTTON_PRESS_PUMP = 23;
	//public static final int CHANGE_BUTTON_RELEASE_PUMP = 29;
	public static final int CHANGE_BUTTON_PRESS_PAUSE = 31;
	//public static final int CHANGE_BUTTON_RELEASE_PAUSE = 37;
	public static final int CHANGE_BUTTON_PRESS_DRAIN = 41;
	public static final int CHANGE_BUTTON_RELEASE_DRAIN = 47;
	public static final int CHANGE_BUTTON_PRESS__PUMPING = 53;
	//public static final int CHANGE_BUTTON_RELEASE_PUMPING = 59;
	//public static final int CHANGE_SCROLL_PWM_PRESS = 61;
	//public static final int CHANGE_SCROLL_PWM_RELEASE = 67;
	public static final int CHANGE_SCROLL_PWM = 71;
	public static final int CHANGE_VALUE_HPRESSURE = 73;
	public static final int CHANGE_VALUE_HHEIGHT = 79;
	
	//public static final int CHANGE_MODE_PAUSE = 103;
	public static final int CHANGE_MODE_CONNECTING = 67;
	public static final int CHANGE_MODE_HANDSHAKING = 61;
	public static final int CHANGE_MODE_IDLE = 83;
	public static final int CHANGE_MODE_DRAIN = 97;
	/**
	 *
	 */
	public static  Enum BUTTON_PUMP_RELEASE_ ;//={Pmp_p};
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonPause;
        private javax.swing.JButton jButtonPump;
        private javax.swing.JButton jButtonRun;
        private javax.swing.JButton jButtonStop;
        private javax.swing.JFormattedTextField jFormattedTextFieldHeghit;
        private javax.swing.JFormattedTextField jFormattedTextFieldPressure;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabelPwm;
        private javax.swing.JLabel jLabelState;
        public javax.swing.JOptionPane jOptionPaneRun;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel13;
        private javax.swing.JPanel jPanel14;
        private javax.swing.JPanel jPanel16;
        private javax.swing.JPanel jPanel17;
        private javax.swing.JPanel jPanel18;
        private javax.swing.JPanel jPanel20;
        private javax.swing.JPanel jPanel21;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanelControl;
        private javax.swing.JPanel jPanelState;
        private javax.swing.JPanel jPanelValve;
        private javax.swing.JRadioButton jRadioButtonHeight;
        private javax.swing.JRadioButton jRadioButtonPressure;
        private javax.swing.JScrollBar jScrollBarPwm;
        private javax.swing.JToggleButton jToggleButtonValveDrain;
        // End of variables declaration//GEN-END:variables
}
