/*
 * Copyright (C) 2024 koalium
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package departed;

import static departed.Form.*;
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author koalium
 */
public class Monitor extends javax.swing.JFrame {

	

	/**
	 * Creates new Form monitoring
	 */
	public Monitor() {
		initComponents();
		
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanelMonitor = new javax.swing.JPanel();
                jPanelMonitorPressure = new javax.swing.JPanel();
                jLabelMonitorPressure = new javax.swing.JLabel();
                jPanelMonitorHeghit = new javax.swing.JPanel();
                jLabelMonitorHeight = new javax.swing.JLabel();
                jPanelMonitorMid = new javax.swing.JPanel();
                jPanelMonitorMidUp = new javax.swing.JPanel();
                jProgressBarMonitorMotorPower = new javax.swing.JProgressBar();
                jLabelMonitorMotorPower = new javax.swing.JLabel();
                jPanelMonitorMidJob = new javax.swing.JPanel();
                jProgressBarJobDone = new javax.swing.JProgressBar();
                jLabelProgressJob = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Monitoring");
                setLocation(new java.awt.Point(10, 153));
                setName("frameMonitor"); // NOI18N

                jPanelMonitor.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitor.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)), javax.swing.BorderFactory.createTitledBorder(null, "Monitoring:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0)))); // NOI18N
                jPanelMonitor.setForeground(new java.awt.Color(153, 153, 255));

                jPanelMonitorPressure.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorPressure.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pressure:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
                jPanelMonitorPressure.setForeground(new java.awt.Color(153, 153, 255));

                jLabelMonitorPressure.setBackground(new java.awt.Color(153, 153, 255));
                jLabelMonitorPressure.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
                jLabelMonitorPressure.setForeground(new java.awt.Color(51, 0, 0));
                jLabelMonitorPressure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelMonitorPressure.setText("101.55");
                jLabelMonitorPressure.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.pink, java.awt.Color.orange));

                javax.swing.GroupLayout jPanelMonitorPressureLayout = new javax.swing.GroupLayout(jPanelMonitorPressure);
                jPanelMonitorPressure.setLayout(jPanelMonitorPressureLayout);
                jPanelMonitorPressureLayout.setHorizontalGroup(
                        jPanelMonitorPressureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorPressureLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMonitorPressure, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelMonitorPressureLayout.setVerticalGroup(
                        jPanelMonitorPressureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorPressureLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMonitorPressure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jPanelMonitorHeghit.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorHeghit.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Height:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 0, 153)))); // NOI18N
                jPanelMonitorHeghit.setForeground(new java.awt.Color(153, 153, 255));

                jLabelMonitorHeight.setBackground(new java.awt.Color(153, 153, 255));
                jLabelMonitorHeight.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
                jLabelMonitorHeight.setForeground(new java.awt.Color(51, 0, 51));
                jLabelMonitorHeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelMonitorHeight.setText("101.55");
                jLabelMonitorHeight.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.pink));

                javax.swing.GroupLayout jPanelMonitorHeghitLayout = new javax.swing.GroupLayout(jPanelMonitorHeghit);
                jPanelMonitorHeghit.setLayout(jPanelMonitorHeghitLayout);
                jPanelMonitorHeghitLayout.setHorizontalGroup(
                        jPanelMonitorHeghitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorHeghitLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMonitorHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelMonitorHeghitLayout.setVerticalGroup(
                        jPanelMonitorHeghitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorHeghitLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMonitorHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jPanelMonitorMid.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorMid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jPanelMonitorMid.setForeground(new java.awt.Color(153, 153, 255));

                jPanelMonitorMidUp.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorMidUp.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "motor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED))); // NOI18N

                jProgressBarMonitorMotorPower.setBackground(new java.awt.Color(153, 153, 153));
                jProgressBarMonitorMotorPower.setForeground(new java.awt.Color(51, 255, 0));
                jProgressBarMonitorMotorPower.setValue(5);

                jLabelMonitorMotorPower.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
                jLabelMonitorMotorPower.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
                jLabelMonitorMotorPower.setForeground(new java.awt.Color(0, 0, 0));
                jLabelMonitorMotorPower.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelMonitorMotorPower.setText("88%");
                jLabelMonitorMotorPower.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                jLabelMonitorMotorPower.setFocusable(false);

                javax.swing.GroupLayout jPanelMonitorMidUpLayout = new javax.swing.GroupLayout(jPanelMonitorMidUp);
                jPanelMonitorMidUp.setLayout(jPanelMonitorMidUpLayout);
                jPanelMonitorMidUpLayout.setHorizontalGroup(
                        jPanelMonitorMidUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorMidUpLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jProgressBarMonitorMotorPower, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMonitorMotorPower, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelMonitorMidUpLayout.setVerticalGroup(
                        jPanelMonitorMidUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMonitorMidUpLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelMonitorMidUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jProgressBarMonitorMotorPower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelMonitorMotorPower, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jLabelMonitorMotorPower.getAccessibleContext().setAccessibleName("");

                jPanelMonitorMidJob.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorMidJob.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "job", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED))); // NOI18N

                jProgressBarJobDone.setBackground(new java.awt.Color(153, 153, 153));
                jProgressBarJobDone.setForeground(new java.awt.Color(153, 255, 255));

                jLabelProgressJob.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
                jLabelProgressJob.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
                jLabelProgressJob.setForeground(new java.awt.Color(0, 0, 0));
                jLabelProgressJob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelProgressJob.setText("66%");

                javax.swing.GroupLayout jPanelMonitorMidJobLayout = new javax.swing.GroupLayout(jPanelMonitorMidJob);
                jPanelMonitorMidJob.setLayout(jPanelMonitorMidJobLayout);
                jPanelMonitorMidJobLayout.setHorizontalGroup(
                        jPanelMonitorMidJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorMidJobLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jProgressBarJobDone, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelProgressJob, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanelMonitorMidJobLayout.setVerticalGroup(
                        jPanelMonitorMidJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorMidJobLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelMonitorMidJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jProgressBarJobDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelProgressJob, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jLabelProgressJob.getAccessibleContext().setAccessibleName("");

                javax.swing.GroupLayout jPanelMonitorMidLayout = new javax.swing.GroupLayout(jPanelMonitorMid);
                jPanelMonitorMid.setLayout(jPanelMonitorMidLayout);
                jPanelMonitorMidLayout.setHorizontalGroup(
                        jPanelMonitorMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorMidLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelMonitorMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanelMonitorMidUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelMonitorMidJob, javax.swing.GroupLayout.PREFERRED_SIZE, 408, Short.MAX_VALUE))
                                .addContainerGap(12, Short.MAX_VALUE))
                );
                jPanelMonitorMidLayout.setVerticalGroup(
                        jPanelMonitorMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorMidLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelMonitorMidUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelMonitorMidJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(14, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanelMonitorLayout = new javax.swing.GroupLayout(jPanelMonitor);
                jPanelMonitor.setLayout(jPanelMonitorLayout);
                jPanelMonitorLayout.setHorizontalGroup(
                        jPanelMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorLayout.createSequentialGroup()
                                .addComponent(jPanelMonitorPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelMonitorMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelMonitorHeghit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                jPanelMonitorLayout.setVerticalGroup(
                        jPanelMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelMonitorLayout.createSequentialGroup()
                                                .addComponent(jPanelMonitorHeghit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addComponent(jPanelMonitorPressure, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelMonitorMid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelMonitor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelMonitor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 804, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 221, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		/* Create and display the Form */
		//</editor-fold>
		//</editor-fold>

		/* Create and display the Form */
		
	}

	//
	//
	//

	
	//
	public synchronized void setmpressure(int mp){
		mpressure=mp;
		jLabelMonitorPressure.setText(""+(float)(mpressure)/100);
		if(fpressure>0 ){
			jPanelMonitorPressure.setBackground(getChangeColor(mpressure,fpressure));
		}
	}
	public synchronized void setmheight(int mp){
		mheight=mp;
		jLabelMonitorHeight.setText(""+(float)(mheight)/100);
		if(fheight>0 ){
			jPanelMonitorHeghit.setBackground(getChangeColor(mheight,fheight));
		}
	}
	public  synchronized void resetmremain(){
		//mremain=mp;
		if(mmode==CHANGE_BUTTON_PRESS_RUN){
			if(mdepend==CHANGE_DEPEND_PRESSURE){
				if(fpressure>0 ){
					mremain = ((mpressure-spressure)*100)/(fpressure);
				}
			}else if(mdepend==CHANGE_DEPEND_HEIGHT){
				if(fheight>0){
					this.mremain=((this.mheight- this.sheight )*100)/(this.fheight);
				}
			}else{
				mremain=0;
			}
		}else{
			
		}
		if(this.fheight>0){
			//this.mremain=((this.mheight- this.sheight )*100)/(this.fheight);
					
			}
		jLabelProgressJob.setText(mremain+"%");
		
		
		jProgressBarJobDone.setValue(mremain);
	}
	public synchronized void setmduty(final int mp){
		mduty=mp;
		jProgressBarMonitorMotorPower.setValue((int)(mduty*100/dutyMax));
		//
		jProgressBarMonitorMotorPower.setForeground(getChangeColor(mduty,dutyMax));
		jLabelMonitorMotorPower.setText(""+(int)(mduty*100/dutyMax)+" %" );
	}
	public synchronized void setmmode(final int mp){
		
		if(this.mmode==CHANGE_MODE_IDLE){
			if(mp==CHANGE_BUTTON_PRESS_RUN){
				
			}
		}else if(mmode==CHANGE_BUTTON_PRESS_RUN){
			if(mp==CHANGE_MODE_IDLE){
				
			}
		}
			
			
		this.mmode=mp;
	}
	public synchronized void setmvalve(final int mp){
	}
	public synchronized void setmfpressure(final int mp){
		this.fpressure=mp;
		if(fpressure>0 &&mdepend==CHANGE_DEPEND_PRESSURE){
			jPanelMonitorPressure.setBackground(getChangeColor(mpressure-spressure,fpressure));
		}
	}
	public synchronized void setmfheight(final int mp){
		this.fheight=mp;
		if(fheight>0 ){
			jPanelMonitorHeghit.setBackground(getChangeColor(mheight-sheight,fheight));
		}
	}
	public synchronized void setstime(final long mp){
	}
	public synchronized void setftime(final long mp){
	}
	public synchronized void setmdepend(final int mp){
		this.mdepend=mp;
		if(this.mdepend ==CHANGE_DEPEND_PRESSURE){
			jLabelMonitorPressure.setBackground(Color.DARK_GRAY);
			jLabelMonitorPressure.setForeground(Color.black);
			jLabelMonitorHeight.setForeground(Color.DARK_GRAY);
		}else{
			jLabelMonitorHeight.setBackground(Color.DARK_GRAY);
			jLabelMonitorHeight.setForeground(Color.black);
			//jLabelMonitorHeight.setFont(font);
			jLabelMonitorPressure.setForeground(Color.DARK_GRAY);
		}
		
	}
	
	public void setmsheight(final int sh){
		this.sheight = sh;
	}
	public void setmspressure(final int sh){
		this.spressure = sh;
	}
	private Color getChangeColor(int val,int max){
		int per = 100*(val);
		Color rc = Color.BLACK;
		if(max==0){
			max = 255;
		}
		per = per/max;
		if(per<25){
			rc = Color.cyan;
		}else
		if(per<55){
			rc = Color.GREEN;
		}else
		if(per<75){
			rc = Color.YELLOW;
		}else
		if(per<85){
			rc = Color.ORANGE;
		}else
		if(per<95){
			rc = Color.pink;
		}else 
		if(per<99){
			rc = Color.magenta;
		}else{
			rc = Color.red;
		}
		
		return rc;
	}
	Timer timer;
	private final int dutyMax=255;	
	private int mpressure=0;
	private int mheight=0;
	private int mremain=0;
	private int mduty=0;
	private int fpressure=0;
	private int fheight=0;
	private int spressure=0;
	private int sheight =0;
	private int mmode=0;
	private int mdepend=CHANGE_DEPEND_HEIGHT;
	public static final int ALETION_CHOOSE = 2;
	public static final int IDLE = 1;
	public static final int NONE = 0;
	public static final int CHANGE_MODE = 2;
	public static final int CHANGE_DEPEND_PRESSURE = 3;
	public static final int CHANGE_DEPEND_HEIGHT = 5;
	public static final int CHANGE_BUTTON_PRESS_RUN = 7;
	//public static final int CHANGE_BUTTON_RELEASE_RUN = 11;
	public static final int CHANGE_BUTTON_PRESS_STOP = 13;
	//public static final int CHANGE_BUTTON_RELEASE_STOP = 17;
	public static final int CHANGE_BUTTON_PRESS_PUMP = 23;
	//public static final int CHANGE_BUTTON_RELEASE_PUMP = 29;
	public static final int CHANGE_BUTTON_PRESS_PAUSE = 31;
	//public static final int CHANGE_BUTTON_RELEASE_PAUSE = 37;
	public static final int CHANGE_BUTTON_PRESS_DRAIN = 41;
	//public static final int CHANGE_BUTTON_RELEASE_DRAIN = 47;
	public static final int CHANGE_BUTTON_PRESS__PUMPING = 53;
	//public static final int CHANGE_BUTTON_RELEASE_PUMPING = 59;
	//public static final int CHANGE_SCROLL_PWM_PRESS = 61;
	//public static final int CHANGE_SCROLL_PWM_RELEASE = 67;
	public static final int CHANGE_SCROLL_PWM = 71;
	public static final int CHANGE_VALUE_HPRESSURE = 73;
	public static final int CHANGE_VALUE_HHEIGHT = 79;
	
	//public static final int CHANGE_MODE_PAUSE = 103;
	public static final int CHANGE_MODE_CONNECTING = 67;
	public static final int CHANGE_MODE_HANDSHAKING = 61;
	public static final int CHANGE_MODE_IDLE = 83;
	public static final int CHANGE_MODE_DRAIN = 97;
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabelMonitorHeight;
        private javax.swing.JLabel jLabelMonitorMotorPower;
        private javax.swing.JLabel jLabelMonitorPressure;
        private javax.swing.JLabel jLabelProgressJob;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanelMonitor;
        private javax.swing.JPanel jPanelMonitorHeghit;
        private javax.swing.JPanel jPanelMonitorMid;
        private javax.swing.JPanel jPanelMonitorMidJob;
        private javax.swing.JPanel jPanelMonitorMidUp;
        private javax.swing.JPanel jPanelMonitorPressure;
        private javax.swing.JProgressBar jProgressBarJobDone;
        private javax.swing.JProgressBar jProgressBarMonitorMotorPower;
        // End of variables declaration//GEN-END:variables
}
